/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLeadsCheckoutRouteImport } from './routes/api/public/leads-checkout'
import { Route as ApiPublicCriarCheckoutStripeRouteImport } from './routes/api/public/criar-checkout-stripe'
import { Route as AuthenticatedAdminTokensRouteImport } from './routes/_authenticated/admin.tokens'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsCheckoutRoute = ApiPublicLeadsCheckoutRouteImport.update({
  id: '/api/public/leads-checkout',
  path: '/api/public/leads-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCriarCheckoutStripeRoute =
  ApiPublicCriarCheckoutStripeRouteImport.update({
    id: '/api/public/criar-checkout-stripe',
    path: '/api/public/criar-checkout-stripe',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminTokensRoute =
  AuthenticatedAdminTokensRouteImport.update({
    id: '/admin/tokens',
    path: '/admin/tokens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/api/public/criar-checkout-stripe': typeof ApiPublicCriarCheckoutStripeRoute
  '/api/public/leads-checkout': typeof ApiPublicLeadsCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/api/public/criar-checkout-stripe': typeof ApiPublicCriarCheckoutStripeRoute
  '/api/public/leads-checkout': typeof ApiPublicLeadsCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/_authenticated/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/api/public/criar-checkout-stripe': typeof ApiPublicCriarCheckoutStripeRoute
  '/api/public/leads-checkout': typeof ApiPublicLeadsCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/admin/tokens'
    | '/api/public/criar-checkout-stripe'
    | '/api/public/leads-checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/admin/tokens'
    | '/api/public/criar-checkout-stripe'
    | '/api/public/leads-checkout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/obrigado'
    | '/_authenticated/admin/tokens'
    | '/api/public/criar-checkout-stripe'
    | '/api/public/leads-checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ObrigadoRoute: typeof ObrigadoRoute
  ApiPublicCriarCheckoutStripeRoute: typeof ApiPublicCriarCheckoutStripeRoute
  ApiPublicLeadsCheckoutRoute: typeof ApiPublicLeadsCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads-checkout': {
      id: '/api/public/leads-checkout'
      path: '/api/public/leads-checkout'
      fullPath: '/api/public/leads-checkout'
      preLoaderRoute: typeof ApiPublicLeadsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/criar-checkout-stripe': {
      id: '/api/public/criar-checkout-stripe'
      path: '/api/public/criar-checkout-stripe'
      fullPath: '/api/public/criar-checkout-stripe'
      preLoaderRoute: typeof ApiPublicCriarCheckoutStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tokens': {
      id: '/_authenticated/admin/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AuthenticatedAdminTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminTokensRoute: typeof AuthenticatedAdminTokensRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminTokensRoute: AuthenticatedAdminTokensRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ObrigadoRoute: ObrigadoRoute,
  ApiPublicCriarCheckoutStripeRoute: ApiPublicCriarCheckoutStripeRoute,
  ApiPublicLeadsCheckoutRoute: ApiPublicLeadsCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
