/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhookCaktoRouteImport } from './routes/api/public/webhook-cakto'
import { Route as ApiPublicWebhookAppmaxRouteImport } from './routes/api/public/webhook-appmax'
import { Route as ApiPublicCriarCheckoutAppmaxRouteImport } from './routes/api/public/criar-checkout-appmax'
import { Route as ApiInternalWhatsappPixPreviewRouteImport } from './routes/api/internal/whatsapp-pix-preview'
import { Route as ApiInternalWhatsappMarkSentRouteImport } from './routes/api/internal/whatsapp-mark-sent'
import { Route as ApiInternalWhatsappFormularioPreviewRouteImport } from './routes/api/internal/whatsapp-formulario-preview'
import { Route as ApiInternalWhatsappCheckoutPreviewRouteImport } from './routes/api/internal/whatsapp-checkout-preview'
import { Route as AuthenticatedAdminTokensRouteImport } from './routes/_authenticated/admin.tokens'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookCaktoRoute = ApiPublicWebhookCaktoRouteImport.update({
  id: '/api/public/webhook-cakto',
  path: '/api/public/webhook-cakto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookAppmaxRoute = ApiPublicWebhookAppmaxRouteImport.update({
  id: '/api/public/webhook-appmax',
  path: '/api/public/webhook-appmax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCriarCheckoutAppmaxRoute =
  ApiPublicCriarCheckoutAppmaxRouteImport.update({
    id: '/api/public/criar-checkout-appmax',
    path: '/api/public/criar-checkout-appmax',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWhatsappPixPreviewRoute =
  ApiInternalWhatsappPixPreviewRouteImport.update({
    id: '/api/internal/whatsapp-pix-preview',
    path: '/api/internal/whatsapp-pix-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWhatsappMarkSentRoute =
  ApiInternalWhatsappMarkSentRouteImport.update({
    id: '/api/internal/whatsapp-mark-sent',
    path: '/api/internal/whatsapp-mark-sent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWhatsappFormularioPreviewRoute =
  ApiInternalWhatsappFormularioPreviewRouteImport.update({
    id: '/api/internal/whatsapp-formulario-preview',
    path: '/api/internal/whatsapp-formulario-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWhatsappCheckoutPreviewRoute =
  ApiInternalWhatsappCheckoutPreviewRouteImport.update({
    id: '/api/internal/whatsapp-checkout-preview',
    path: '/api/internal/whatsapp-checkout-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminTokensRoute =
  AuthenticatedAdminTokensRouteImport.update({
    id: '/admin/tokens',
    path: '/admin/tokens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/api/internal/whatsapp-checkout-preview': typeof ApiInternalWhatsappCheckoutPreviewRoute
  '/api/internal/whatsapp-formulario-preview': typeof ApiInternalWhatsappFormularioPreviewRoute
  '/api/internal/whatsapp-mark-sent': typeof ApiInternalWhatsappMarkSentRoute
  '/api/internal/whatsapp-pix-preview': typeof ApiInternalWhatsappPixPreviewRoute
  '/api/public/criar-checkout-appmax': typeof ApiPublicCriarCheckoutAppmaxRoute
  '/api/public/webhook-appmax': typeof ApiPublicWebhookAppmaxRoute
  '/api/public/webhook-cakto': typeof ApiPublicWebhookCaktoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/api/internal/whatsapp-checkout-preview': typeof ApiInternalWhatsappCheckoutPreviewRoute
  '/api/internal/whatsapp-formulario-preview': typeof ApiInternalWhatsappFormularioPreviewRoute
  '/api/internal/whatsapp-mark-sent': typeof ApiInternalWhatsappMarkSentRoute
  '/api/internal/whatsapp-pix-preview': typeof ApiInternalWhatsappPixPreviewRoute
  '/api/public/criar-checkout-appmax': typeof ApiPublicCriarCheckoutAppmaxRoute
  '/api/public/webhook-appmax': typeof ApiPublicWebhookAppmaxRoute
  '/api/public/webhook-cakto': typeof ApiPublicWebhookCaktoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/_authenticated/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/api/internal/whatsapp-checkout-preview': typeof ApiInternalWhatsappCheckoutPreviewRoute
  '/api/internal/whatsapp-formulario-preview': typeof ApiInternalWhatsappFormularioPreviewRoute
  '/api/internal/whatsapp-mark-sent': typeof ApiInternalWhatsappMarkSentRoute
  '/api/internal/whatsapp-pix-preview': typeof ApiInternalWhatsappPixPreviewRoute
  '/api/public/criar-checkout-appmax': typeof ApiPublicCriarCheckoutAppmaxRoute
  '/api/public/webhook-appmax': typeof ApiPublicWebhookAppmaxRoute
  '/api/public/webhook-cakto': typeof ApiPublicWebhookCaktoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/admin/tokens'
    | '/api/internal/whatsapp-checkout-preview'
    | '/api/internal/whatsapp-formulario-preview'
    | '/api/internal/whatsapp-mark-sent'
    | '/api/internal/whatsapp-pix-preview'
    | '/api/public/criar-checkout-appmax'
    | '/api/public/webhook-appmax'
    | '/api/public/webhook-cakto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/admin/tokens'
    | '/api/internal/whatsapp-checkout-preview'
    | '/api/internal/whatsapp-formulario-preview'
    | '/api/internal/whatsapp-mark-sent'
    | '/api/internal/whatsapp-pix-preview'
    | '/api/public/criar-checkout-appmax'
    | '/api/public/webhook-appmax'
    | '/api/public/webhook-cakto'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/obrigado'
    | '/_authenticated/admin/tokens'
    | '/api/internal/whatsapp-checkout-preview'
    | '/api/internal/whatsapp-formulario-preview'
    | '/api/internal/whatsapp-mark-sent'
    | '/api/internal/whatsapp-pix-preview'
    | '/api/public/criar-checkout-appmax'
    | '/api/public/webhook-appmax'
    | '/api/public/webhook-cakto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ObrigadoRoute: typeof ObrigadoRoute
  ApiInternalWhatsappCheckoutPreviewRoute: typeof ApiInternalWhatsappCheckoutPreviewRoute
  ApiInternalWhatsappFormularioPreviewRoute: typeof ApiInternalWhatsappFormularioPreviewRoute
  ApiInternalWhatsappMarkSentRoute: typeof ApiInternalWhatsappMarkSentRoute
  ApiInternalWhatsappPixPreviewRoute: typeof ApiInternalWhatsappPixPreviewRoute
  ApiPublicCriarCheckoutAppmaxRoute: typeof ApiPublicCriarCheckoutAppmaxRoute
  ApiPublicWebhookAppmaxRoute: typeof ApiPublicWebhookAppmaxRoute
  ApiPublicWebhookCaktoRoute: typeof ApiPublicWebhookCaktoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook-cakto': {
      id: '/api/public/webhook-cakto'
      path: '/api/public/webhook-cakto'
      fullPath: '/api/public/webhook-cakto'
      preLoaderRoute: typeof ApiPublicWebhookCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook-appmax': {
      id: '/api/public/webhook-appmax'
      path: '/api/public/webhook-appmax'
      fullPath: '/api/public/webhook-appmax'
      preLoaderRoute: typeof ApiPublicWebhookAppmaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/criar-checkout-appmax': {
      id: '/api/public/criar-checkout-appmax'
      path: '/api/public/criar-checkout-appmax'
      fullPath: '/api/public/criar-checkout-appmax'
      preLoaderRoute: typeof ApiPublicCriarCheckoutAppmaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/whatsapp-pix-preview': {
      id: '/api/internal/whatsapp-pix-preview'
      path: '/api/internal/whatsapp-pix-preview'
      fullPath: '/api/internal/whatsapp-pix-preview'
      preLoaderRoute: typeof ApiInternalWhatsappPixPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/whatsapp-mark-sent': {
      id: '/api/internal/whatsapp-mark-sent'
      path: '/api/internal/whatsapp-mark-sent'
      fullPath: '/api/internal/whatsapp-mark-sent'
      preLoaderRoute: typeof ApiInternalWhatsappMarkSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/whatsapp-formulario-preview': {
      id: '/api/internal/whatsapp-formulario-preview'
      path: '/api/internal/whatsapp-formulario-preview'
      fullPath: '/api/internal/whatsapp-formulario-preview'
      preLoaderRoute: typeof ApiInternalWhatsappFormularioPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/whatsapp-checkout-preview': {
      id: '/api/internal/whatsapp-checkout-preview'
      path: '/api/internal/whatsapp-checkout-preview'
      fullPath: '/api/internal/whatsapp-checkout-preview'
      preLoaderRoute: typeof ApiInternalWhatsappCheckoutPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tokens': {
      id: '/_authenticated/admin/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AuthenticatedAdminTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminTokensRoute: typeof AuthenticatedAdminTokensRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminTokensRoute: AuthenticatedAdminTokensRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ObrigadoRoute: ObrigadoRoute,
  ApiInternalWhatsappCheckoutPreviewRoute:
    ApiInternalWhatsappCheckoutPreviewRoute,
  ApiInternalWhatsappFormularioPreviewRoute:
    ApiInternalWhatsappFormularioPreviewRoute,
  ApiInternalWhatsappMarkSentRoute: ApiInternalWhatsappMarkSentRoute,
  ApiInternalWhatsappPixPreviewRoute: ApiInternalWhatsappPixPreviewRoute,
  ApiPublicCriarCheckoutAppmaxRoute: ApiPublicCriarCheckoutAppmaxRoute,
  ApiPublicWebhookAppmaxRoute: ApiPublicWebhookAppmaxRoute,
  ApiPublicWebhookCaktoRoute: ApiPublicWebhookCaktoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
